
export class FintechResponse {
  static get HTTP_OK() {
    return 200;
  }

  static get HTTP_CREATED() {
    return 201;
  }

  static get HTTP_ACCEPTED() {
    return 202;
  }

  static get HTTP_NO_CONTENT() {
    return 204;
  }

  static get HTTP_BAD_REQUEST() {
    return 400;
  }

  static get HTTP_UNAUTHORIZED() {
    return 401;
  }

  static get HTTP_FORBIDDEN() {
    return 403;
  }

  static get HTTP_NOT_FOUND() {
    return 404;
  }

  static get HTTP_METHOD_NOT_ALLOWED() {
    return 405;
  }

  static get HTTP_CONFLICT() {
    return 409;
  }

  static get HTTP_INTERNAL_SERVER_ERROR() {
    return 500;
  }

  static getMessages() {
    return {
      VALIDATIONERROR: "PLEASE FILL IN ALL REQUIRED FIELDS",
      SUCCESS: "SUCESSFUL",
      INVALIDCURRENCY: "KINDLY INPUT A VALID CURRENCY (USD OR EUR)",
      BADREQUESTROLE: "CHECK ROLE AND RETRY",
      EMAILEXISTS: "EMAIL ALREADY EXISTS",
      GUESTUSER: "GUEST USER ALREADY EXISTS",
      ERROR: "AN ERROR OCCURRED",
      WRONGEMAILFORMAT: "WRONG EMAIL FORMAT",
      WRONGPARAMETERS: "INVALID CREDENTIALS",
      NORECORD: "INVALID USER",
      PASSWORDERROR: "PASSWORD DOES NOT EXIST FOR THE USER",
      INACTIVEUSER: "YOU'RE CURRENTLY INACTIVE",
      EXPIREDTOKEN: "KINDLY REQUEST AGAIN TOKEN HAS EXPIRED",
      INVALIDTOKEN: "KINDLY REQUEST AGAIN TOKEN IS INVALID",
      UNAVAILABLERESOURCE: "RESOURCE IS CURRENTLY UNAVAILABLE",
      ACCESSDENIED: "NOT AUTHORIZED",
      WRONGPASSFORMAT: "INVALID PASSWORD FORMAT",
      MAILVERIFICATION: "KINDLY VERIFY EMAIL",
      ACCOUNTRESTRICTION: "KINDLY CONTACT SUPPORT, ACCOUNT IS INACTIVE",
      USERNOTFOUND: "USER DOES NOT EXIST, TRY AGAIN WITH A VALID USER",
      ADMINNOTFOUND: "ADMIN DOES NOT EXIST, TRY AGAIN USING A VALID ADMIN",
      WALLETNOTFOUND: "NO AVAILABLE INFO ON THIS WALLET",
      INSUFFICIENTFUNDS: "KINDLY CREDIT ACCOUNT, INSUFFICIENT FUNDS",
      ACCOUNTSNOTDIFFERENT: "ORIGINATOR ACCOUNT MUST BE DIFFERENT FROM BENEFICIARY LIKEWISE",
      ACCOUNTNUMBEREXISTS: "ACCOUNT NUMBER ALREADY EXISTS"
    };
  }

  static responseMessages() {
    return {
      VALIDATIONERROR: "VALIDATION ERROR",
      NORECORD: "NOT FOUND",
      BADREQUEST: "BAD REQUEST",
      FORMATERROR: "INVALID FORMAT",
      REGISTRATIONSUCCESS: "SUCCESSFUL",
      ERROR: "AN ERROR OCCURRED",
      CONFLICT: "RESOURCE ALREADY EXISTS",
      ACCESSDENIED: "FORBIDDEN",
      UPDATEDSTATUS: "STATUS UPDATED SUCCESSFULLY",
    };
  }
}
